#:kivy 2.2.1

<Portfolio>:
    name: 'portfolio'
    MDBoxLayout:
        orientation: "vertical"
        size_hint: 1, 1

        MDTopAppBar:
            title: "Portfolio"
            left_action_items: [["arrow-left", lambda x: app.root.set_current('main')]]

        Image:
            id: graph
            source: 'images/piechartbase.png'
            size: self.parent.size
            size_hint: 1, .5

        MDBoxLayout:
            id: table
            size_hint: 1, .5